CREATE SCHEMA HIAS;

--SET UP Client
CREATE TABLE HIAS.CLIENT
(
    CLIENT_NO   INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CLIENT_NAME VARCHAR(2000),
    CLIENT_ID   VARCHAR(2000),
    CREATED_BY  VARCHAR(2000),
    CREATED_ON  TIMESTAMP,
    MODIFIED_BY VARCHAR(2000),
    MODIFIED_ON TIMESTAMP
);

CREATE TABLE HIAS.CLIENT
(
    CLIENT_NO   INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CLIENT_NAME VARCHAR(2000),
    CLIENT_ID   VARCHAR(2000),
    CREATED_BY  VARCHAR(2000),
    CREATED_ON  TIMESTAMP,
    MODIFIED_BY VARCHAR(2000),
    MODIFIED_ON TIMESTAMP
);