--TRIGGER SETUP CLAIM ID
CREATE
OR REPLACE FUNCTION HIAS.SETUP_CLAIMID()
  RETURNS trigger AS
$$
BEGIN
    NEW.CLAIM_ID
:= concat('CL','',NEW.CLAIM_NO);
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER TRIGGER_SETUP_CLAIM_ID
    BEFORE INSERT
    ON HIAS.CLAIM
    FOR EACH ROW
    EXECUTE PROCEDURE HIAS.SETUP_CLAIMID();